//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAIGameWeb.GameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.IGameServerService")]
    public interface IGameServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/WantsToPlay", ReplyAction="http://tempuri.org/IGameServerService/WantsToPlayResponse")]
        void WantsToPlay(string userId, string ai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/WantsToPlay", ReplyAction="http://tempuri.org/IGameServerService/WantsToPlayResponse")]
        System.Threading.Tasks.Task WantsToPlayAsync(string userId, string ai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/StartGame", ReplyAction="http://tempuri.org/IGameServerService/StartGameResponse")]
        void StartGame(string userId1, string userId2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/StartGame", ReplyAction="http://tempuri.org/IGameServerService/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(string userId1, string userId2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServerServiceChannel : FootballAIGameWeb.GameService.IGameServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServerServiceClient : System.ServiceModel.ClientBase<FootballAIGameWeb.GameService.IGameServerService>, FootballAIGameWeb.GameService.IGameServerService {
        
        public GameServerServiceClient() {
        }
        
        public GameServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WantsToPlay(string userId, string ai) {
            base.Channel.WantsToPlay(userId, ai);
        }
        
        public System.Threading.Tasks.Task WantsToPlayAsync(string userId, string ai) {
            return base.Channel.WantsToPlayAsync(userId, ai);
        }
        
        public void StartGame(string userId1, string userId2) {
            base.Channel.StartGame(userId1, userId2);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string userId1, string userId2) {
            return base.Channel.StartGameAsync(userId1, userId2);
        }
    }
}
