// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FootballAIGame.Web.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixMispelledWord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixMispelledWord));
        
        string IMigrationMetadata.Id
        {
            get { return "201611300339237_FixMispelledWord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
