//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAIGameWeb.GameServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameServerService.IGameServerService")]
    public interface IGameServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/WantsToPlay", ReplyAction="http://tempuri.org/IGameServerService/WantsToPlayResponse")]
        string WantsToPlay(string userName, string ai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/WantsToPlay", ReplyAction="http://tempuri.org/IGameServerService/WantsToPlayResponse")]
        System.Threading.Tasks.Task<string> WantsToPlayAsync(string userName, string ai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/StartGame", ReplyAction="http://tempuri.org/IGameServerService/StartGameResponse")]
        string StartGame(string userName1, string ai1, string userName2, string ai2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServerService/StartGame", ReplyAction="http://tempuri.org/IGameServerService/StartGameResponse")]
        System.Threading.Tasks.Task<string> StartGameAsync(string userName1, string ai1, string userName2, string ai2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServerServiceChannel : FootballAIGameWeb.GameServerService.IGameServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServerServiceClient : System.ServiceModel.ClientBase<FootballAIGameWeb.GameServerService.IGameServerService>, FootballAIGameWeb.GameServerService.IGameServerService {
        
        public GameServerServiceClient() {
        }
        
        public GameServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WantsToPlay(string userName, string ai) {
            return base.Channel.WantsToPlay(userName, ai);
        }
        
        public System.Threading.Tasks.Task<string> WantsToPlayAsync(string userName, string ai) {
            return base.Channel.WantsToPlayAsync(userName, ai);
        }
        
        public string StartGame(string userName1, string ai1, string userName2, string ai2) {
            return base.Channel.StartGame(userName1, ai1, userName2, ai2);
        }
        
        public System.Threading.Tasks.Task<string> StartGameAsync(string userName1, string ai1, string userName2, string ai2) {
            return base.Channel.StartGameAsync(userName1, ai1, userName2, ai2);
        }
    }
}
